import "./globals.scss";
import { Analytics } from "@vercel/analytics/react"
import { NextUIProvider } from "@nextui-org/react";
import Header from "./components/Header";
import Footer from "./components/footer";
import i18nConfig from "@/i18nConfig";
import getIntl from "../../app/intl";
import ServerIntlProvider from "./components/ServerIntlProvider";

export const metadata = {
  title: "Alexander",
  description: "Generated by create next app",
};

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function RootLayout({ children, params }) {
  const { locale } = params;
  const intl = await getIntl(locale);
  return (
    <html lang={locale}>
      <body>
        <ServerIntlProvider messages={intl.messages} locale={intl.locale}>
          <NextUIProvider>
            <Header />
            <main>{children}</main>
            <Analytics />
            <Footer params={{ locale }}/>
          </NextUIProvider>
        </ServerIntlProvider>
      </body>
    </html>
  );
}
